import { useCallback, useEffect, useState } from 'react'
import { getRouteApi } from '@tanstack/react-router'
import { LayoutGrid, Table2 } from 'lucide-react'
import { handleServerError } from '@/lib/handle-server-error'
import { Button } from '@/components/ui/button'
import { ThemeSwitch } from '@/components/theme-switch'
import { AccountsDialogs } from './components/accounts-dialogs'
import { AccountsKanban } from './components/accounts-kanban'
import { AccountsPrimaryButtons } from './components/accounts-primary-buttons'
import { AccountsProvider } from './components/accounts-provider'
import { AccountsTable } from './components/accounts-table'
import { getMockAccounts } from './data/mock-data'
import type { Account } from './data/schema'

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - Route type will be generated by TanStack Router plugin when dev server runs
const route = getRouteApi('/accounts/')

export function Accounts() {
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore - Search type will be generated by TanStack Router plugin
  const search = route.useSearch() as {
    page?: number
    pageSize?: number
    name?: string
    code?: string
    accountType?: string[]
    active?: string[]
  }
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore - Navigate type will be generated by TanStack Router plugin
  const navigate = route.useNavigate() as (opts: {
    search:
      | true
      | Record<string, unknown>
      | ((
          prev: Record<string, unknown>
        ) => Partial<Record<string, unknown>> | Record<string, unknown>)
    replace?: boolean
  }) => void
  const [accounts, setAccounts] = useState<Account[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [total, setTotal] = useState(0)
  const [refreshKey, setRefreshKey] = useState(0)
  const [viewMode, setViewMode] = useState<'table' | 'kanban'>('table')

  // 开发模式下使用模拟数据（默认启用，可通过环境变量 VITE_USE_MOCK_DATA=false 禁用）
  const useMockData =
    import.meta.env.DEV && import.meta.env.VITE_USE_MOCK_DATA !== 'false'

  /**
   * 获取科目列表
   */
  useEffect(() => {
    async function fetchAccounts() {
      setIsLoading(true)
      try {
        // 从 URL 搜索参数获取分页和筛选信息
        const current = search.page || 1
        const pageSize = search.pageSize || 10
        const name = search.name as string | undefined
        const code = search.code as string | undefined
        const accountTypeFilter = search.accountType as string[] | undefined
        const activeFilter = search.active as string[] | undefined

        // 将前端状态转换为后端状态
        let backendAccountType: Account['accountType'] | undefined = undefined
        if (accountTypeFilter && accountTypeFilter.length > 0) {
          backendAccountType = accountTypeFilter[0] as Account['accountType']
        }

        let backendActive: boolean | undefined = undefined
        if (activeFilter && activeFilter.length > 0) {
          backendActive = activeFilter.includes('active')
        }

        // 使用模拟数据或真实 API
        if (useMockData) {
          // 模拟 API 延迟
          await new Promise((resolve) => setTimeout(resolve, 300))

          const mockResponse = getMockAccounts({
            current,
            size: pageSize,
            name,
            code,
            accountType: backendAccountType,
            active: backendActive,
          })

          setAccounts(mockResponse.records)
          setTotal(mockResponse.total)
        } else {
          // TODO: 实现真实的 API 调用
          // const response = await accountService.getAccountList({...})
          // if (response.data) {
          //   setAccounts(response.data.records)
          //   setTotal(response.data.total)
          // }
        }
      } catch (error) {
        handleServerError(error)
      } finally {
        setIsLoading(false)
      }
    }

    fetchAccounts()
  }, [
    search.page,
    search.pageSize,
    search.name,
    search.code,
    search.accountType,
    search.active,
    refreshKey,
    useMockData,
  ])

  /**
   * 刷新科目列表
   */
  const refreshAccounts = useCallback(() => {
    setRefreshKey((prev) => prev + 1)
  }, [])

  return (
    <div className='flex min-h-screen flex-col'>
      {/* 简化的 Header，不依赖认证上下文 */}
      <header className='bg-background/95 supports-[backdrop-filter]:bg-background/60 sticky top-0 z-50 border-b backdrop-blur'>
        <div className='container flex h-16 items-center justify-between px-4'>
          <div className='flex items-center gap-2'>
            <h1 className='text-lg font-bold'>科目表</h1>
          </div>
          <div className='flex items-center space-x-4'>
            <ThemeSwitch />
          </div>
        </div>
      </header>

      {/* 主要内容区域 */}
      <main className='container flex flex-1 flex-col gap-4 px-4 py-6 sm:gap-6'>
        <AccountsProvider refreshAccounts={refreshAccounts}>
          <div className='flex flex-wrap items-end justify-between gap-2'>
            <div>
              <h2 className='text-2xl font-bold tracking-tight'>科目表</h2>
              <p className='text-muted-foreground'>在此管理您的会计科目。</p>
            </div>
            <div className='flex items-center gap-2'>
              {/* 视图切换按钮 */}
              <div className='bg-muted inline-flex rounded-lg p-1'>
                <Button
                  variant={viewMode === 'table' ? 'default' : 'ghost'}
                  size='sm'
                  onClick={() => setViewMode('table')}
                  className='gap-2'
                >
                  <Table2 size={16} />
                  表格
                </Button>
                <Button
                  variant={viewMode === 'kanban' ? 'default' : 'ghost'}
                  size='sm'
                  onClick={() => setViewMode('kanban')}
                  className='gap-2'
                >
                  <LayoutGrid size={16} />
                  看板
                </Button>
              </div>
              <AccountsPrimaryButtons />
            </div>
          </div>
          {isLoading ? (
            <div className='flex items-center justify-center py-8'>
              <p className='text-muted-foreground'>加载中...</p>
            </div>
          ) : viewMode === 'table' ? (
            <AccountsTable
              data={accounts}
              search={search}
              navigate={navigate}
              total={total}
            />
          ) : (
            <AccountsKanban data={accounts} />
          )}

          <AccountsDialogs />
        </AccountsProvider>
      </main>
    </div>
  )
}
