import { useCallback, useEffect, useState } from 'react'
import { getRouteApi } from '@tanstack/react-router'
import { LayoutGrid, Table2 } from 'lucide-react'
import { adaptProductTemplateListResponse } from '@/lib/adapters/product-template.adapter'
import { handleServerError } from '@/lib/handle-server-error'
import { productTemplateService } from '@/lib/services/product-template.service'
import { Button } from '@/components/ui/button'
import { ThemeSwitch } from '@/components/theme-switch'
import { ProductTemplatesDialogs } from './components/product-templates-dialogs'
import { ProductTemplatesKanban } from './components/product-templates-kanban'
import { ProductTemplatesPrimaryButtons } from './components/product-templates-primary-buttons'
import { ProductTemplatesProvider } from './components/product-templates-provider'
import { ProductTemplatesTable } from './components/product-templates-table'
import { getMockProductTemplates } from './data/mock-data'
import type { ProductTemplate } from './data/schema'

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - Route type will be generated by TanStack Router plugin when dev server runs
const route = getRouteApi('/product-templates/')

export function ProductTemplates() {
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore - Search type will be generated by TanStack Router plugin
  const search = route.useSearch() as {
    page?: number
    pageSize?: number
    name?: string
    code?: string
    type?: string[]
    active?: string[]
  }
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore - Navigate type will be generated by TanStack Router plugin
  const navigate = route.useNavigate() as (opts: {
    search:
      | true
      | Record<string, unknown>
      | ((
          prev: Record<string, unknown>
        ) => Partial<Record<string, unknown>> | Record<string, unknown>)
    replace?: boolean
  }) => void
  const [productTemplates, setProductTemplates] = useState<ProductTemplate[]>(
    []
  )
  const [isLoading, setIsLoading] = useState(true)
  const [total, setTotal] = useState(0)
  const [refreshKey, setRefreshKey] = useState(0)
  const [viewMode, setViewMode] = useState<'table' | 'kanban'>('table')

  // 开发模式下使用模拟数据（默认启用，可通过环境变量 VITE_USE_MOCK_DATA=false 禁用）
  const useMockData =
    import.meta.env.DEV && import.meta.env.VITE_USE_MOCK_DATA !== 'false'

  /**
   * 获取产品模板列表
   */
  useEffect(() => {
    async function fetchProductTemplates() {
      setIsLoading(true)
      try {
        // 从 URL 搜索参数获取分页和筛选信息
        const current = search.page || 1
        const pageSize = search.pageSize || 10
        const name = search.name as string | undefined
        const code = search.code as string | undefined
        const typeFilter = search.type as string[] | undefined
        const activeFilter = search.active as string[] | undefined

        // 将前端状态转换为后端状态
        let backendType: 'product' | 'service' | 'consu' | undefined = undefined
        if (typeFilter && typeFilter.length > 0) {
          backendType = typeFilter[0] as 'product' | 'service' | 'consu'
        }

        let backendActive: boolean | undefined = undefined
        if (activeFilter && activeFilter.length > 0) {
          backendActive = activeFilter.includes('active')
        }

        // 使用模拟数据或真实 API
        if (useMockData) {
          // 模拟 API 延迟
          await new Promise((resolve) => setTimeout(resolve, 300))

          const mockResponse = getMockProductTemplates({
            current,
            size: pageSize,
            name,
            code,
            type: backendType,
            active: backendActive,
          })

          const adapted = adaptProductTemplateListResponse(mockResponse)
          setProductTemplates(adapted.productTemplates)
          setTotal(adapted.total)
        } else {
          const response = await productTemplateService.getProductTemplateList({
            current,
            size: pageSize,
            name,
            code,
            type: backendType,
            active: backendActive,
          })

          if (response.data) {
            const adapted = adaptProductTemplateListResponse(response.data)
            setProductTemplates(adapted.productTemplates)
            setTotal(adapted.total)
          }
        }
      } catch (error) {
        handleServerError(error)
      } finally {
        setIsLoading(false)
      }
    }

    fetchProductTemplates()
  }, [
    search.page,
    search.pageSize,
    search.name,
    search.code,
    search.type,
    search.active,
    refreshKey,
    useMockData,
  ])

  /**
   * 刷新产品模板列表
   */
  const refreshProductTemplates = useCallback(() => {
    setRefreshKey((prev) => prev + 1)
  }, [])

  return (
    <div className='flex min-h-screen flex-col'>
      {/* 简化的 Header，不依赖认证上下文 */}
      <header className='bg-background/95 supports-[backdrop-filter]:bg-background/60 sticky top-0 z-50 border-b backdrop-blur'>
        <div className='container flex h-16 items-center justify-between px-4'>
          <div className='flex items-center gap-2'>
            <h1 className='text-lg font-bold'>产品模板</h1>
          </div>
          <div className='flex items-center space-x-4'>
            <ThemeSwitch />
          </div>
        </div>
      </header>

      {/* 主要内容区域 */}
      <main className='container flex flex-1 flex-col gap-4 px-4 py-6 sm:gap-6'>
        <ProductTemplatesProvider
          refreshProductTemplates={refreshProductTemplates}
        >
          <div className='flex flex-wrap items-end justify-between gap-2'>
            <div>
              <h2 className='text-2xl font-bold tracking-tight'>产品模板</h2>
              <p className='text-muted-foreground'>在此管理您的产品模板。</p>
            </div>
            <div className='flex items-center gap-2'>
              {/* 视图切换按钮 */}
              <div className='bg-muted inline-flex rounded-lg p-1'>
                <Button
                  variant={viewMode === 'table' ? 'default' : 'ghost'}
                  size='sm'
                  onClick={() => setViewMode('table')}
                  className='gap-2'
                >
                  <Table2 size={16} />
                  表格
                </Button>
                <Button
                  variant={viewMode === 'kanban' ? 'default' : 'ghost'}
                  size='sm'
                  onClick={() => setViewMode('kanban')}
                  className='gap-2'
                >
                  <LayoutGrid size={16} />
                  看板
                </Button>
              </div>
              <ProductTemplatesPrimaryButtons />
            </div>
          </div>
          {isLoading ? (
            <div className='flex items-center justify-center py-8'>
              <p className='text-muted-foreground'>加载中...</p>
            </div>
          ) : viewMode === 'table' ? (
            <ProductTemplatesTable
              data={productTemplates}
              search={search}
              navigate={navigate}
              total={total}
            />
          ) : (
            <ProductTemplatesKanban data={productTemplates} />
          )}

          <ProductTemplatesDialogs />
        </ProductTemplatesProvider>
      </main>
    </div>
  )
}
