import z from 'zod'
import { createFileRoute } from '@tanstack/react-router'
import { ProductTemplates } from '@/features/product-templates'

const productTemplatesSearchSchema = z.object({
  page: z.number().optional().catch(1),
  pageSize: z.number().optional().catch(10),
  // Facet filters
  type: z
    .array(
      z.union([z.literal('product'), z.literal('service'), z.literal('consu')])
    )
    .optional()
    .catch([]),
  active: z
    .array(z.union([z.literal('active'), z.literal('inactive')]))
    .optional()
    .catch([]),
  // Per-column text filters
  name: z.string().optional().catch(''),
  code: z.string().optional().catch(''),
})

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - Route type will be generated by TanStack Router plugin when dev server runs
export const Route = createFileRoute('/product-templates/')({
  validateSearch: productTemplatesSearchSchema,
  component: ProductTemplates,
})
