import z from 'zod'
import { createFileRoute } from '@tanstack/react-router'
import { Accounts } from '@/features/accounts'

const accountsSearchSchema = z.object({
  page: z.number().optional().catch(1),
  pageSize: z.number().optional().catch(10),
  // Facet filters
  accountType: z
    .array(
      z.union([
        z.literal('asset_receivable'),
        z.literal('asset_cash'),
        z.literal('asset_current'),
        z.literal('asset_non_current'),
        z.literal('asset_fixed'),
        z.literal('asset_prepayments'),
        z.literal('liability_payable'),
        z.literal('liability_credit_card'),
        z.literal('liability_current'),
        z.literal('liability_non_current'),
        z.literal('equity'),
        z.literal('equity_unaffected'),
        z.literal('income'),
        z.literal('expense'),
        z.literal('expense_depreciation'),
        z.literal('expense_direct_cost'),
        z.literal('off_balance'),
      ])
    )
    .optional()
    .catch([]),
  active: z
    .array(z.union([z.literal('active'), z.literal('inactive')]))
    .optional()
    .catch([]),
  // Per-column text filters
  name: z.string().optional().catch(''),
  code: z.string().optional().catch(''),
})

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - Route type will be generated by TanStack Router plugin when dev server runs
export const Route = createFileRoute('/accounts/')({
  validateSearch: accountsSearchSchema,
  component: Accounts,
})
